
function(get_target_type TARGET TARGET_TYPE)
  get_target_property(target_type ${TARGET} TYPE)

  if(target_type STREQUAL "EXECUTABLE")
    set(${TARGET_TYPE} "EXECUTABLE" PARENT_SCOPE)
  elseif(target_type STREQUAL "STATIC_LIBRARY")
    set(${TARGET_TYPE} "STATIC_LIBRARY" PARENT_SCOPE)
  elseif(target_type STREQUAL "SHARED_LIBRARY")
    set(${TARGET_TYPE} "SHARED_LIBRARY" PARENT_SCOPE)
  elseif(target_type STREQUAL "MODULE_LIBRARY")
    set(${TARGET_TYPE} "MODULE_LIBRARY" PARENT_SCOPE)
  elseif(target_type STREQUAL "OBJECT_LIBRARY")
    set(${TARGET_TYPE} "OBJECT_LIBRARY" PARENT_SCOPE)
  elseif(target_type STREQUAL "INTERFACE_LIBRARY")
    set(${TARGET_TYPE} "INTERFACE_LIBRARY" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "Target ${TARGET} unknown type ${target_type}")
  endif()
endfunction()
