/*
 @ 0xCCCCCCCC
*/

#if defined(_MSC_VER)
#pragma once
#endif

#ifndef CAPTURE_STACK_TRACE_STACK_WALKER_H_
#define CAPTURE_STACK_TRACE_STACK_WALKER_H_

#endif  // CAPTURE_STACK_TRACE_STACK_WALKER_H_
